---
- name: AWS EC2 Automation Playbook
  hosts: localhost
  gather_facts: false

  vars_files:
    - AWS-VPC/vars/info.yml
  
  tasks:
    - name: create a VPC
      ec2_vpc_net:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: test_vpc_net
        cidr_block: 10.0.0.0/16
        tags:
          module: ec2_vpc_net
        tenancy: default
      register: ansibleVPC
    
    - name: Display the ansibleVPC output
      debug:
        var: ansibleVPC